---
# tasks file for batandwa.ansible-phusion-baseimage

- name: Check if container exists
  shell: docker inspect {{ container.container_name }} || false
  ignore_errors: yes
  register: command_result

- name: Check if data container exists
  shell: docker inspect {{ container.container_name }} || false
  ignore_errors: yes
  register: data_container_exists

- name: Stop and remove existing container container
  shell: docker stop {{ container.container_name }} && docker rm {{ container.container_name }}
  when: container.container_kill_existing and command_result.rc == 0

- name: Run a data-only container
  docker: image=ubuntu:14.04 name={{ container.container_name }}_data command=/bin/bash detach=yes volumes={{ container.container_volumes | join(',') }}


- name: Run the main container
  shell: docker run -d {{ ' '.join(container.container_ports) }} --volumes-from={{ container.container_name }}_data {{ ' '.join(container.container_extra) }} --hostname={{ container.container_domain }} --name={{ container.container_name }} {{ container.container_image }} {{ container.container_command }}
  when: (container.container_kill_existing or command_result.rc != 0)


- name: Make sure the container is started
  shell: docker start {{ container.container_name }}
