---
- name: Start a volume container
  docker: 
    image: "ubuntu" 
    name: "{{ item.key }}_vol" 
    command: "/bin/bash" 
    detach: yes 
    volumes: "{{ item.value.container_volumes }}"
  with_dict: containers

- name: Start a container
  docker: 
    image: "{{ item.value.container_image }}" 
    name: "{{ item.key }}" 
    command: "{{ item.value.container_command }}" 
    hostname: "{{ item.value.container_domain }}" 
    detach: yes 
    ports: "{{ item.value.container_ports }}"
    volumes_from: "{{ item.key }}_vol" 
    publish_all_ports: "{{ item.value.container_all_ports }}"
    docker_url: "{{ item.value.container_docker_url }}"
  with_dict: containers
