---
# tasks file for batandwa.ansible-phusion-baseimage

# - shell: echo "{{ item }}"
#   with_items: docker_containers
#   register: echo

- name: Stop container
  # command: docker kill {{ container_name }}
  docker: state=killed name={{ container_name }} image={{ container_image }}
  when: container_kill_existing == "Y" or container_kill_existing == "y"



# - name: Destroy container
#   command: docker rm {{ name }} 

- name: Start a volume container
  docker: image="ubuntu" name="{{ container_name }}_vol" command="/bin/bash" detach=yes volumes="{{ container_volumes }}"

- name: Start a container
  docker: image="{{ container_image }}" name="{{ container_name }}" command="{{ container_command }}" detach=yes ports="{{ container_ports }}" volumes_from="{{ container_name }}_vol" publish_all_ports="{{ container_all_ports }}"

- name: New container IP
  debug: msg={{ item['NetworkSettings']['IPAddress'] }}
  with_items: docker_containers

# - name: Create hosts file
#   command: "echo {{ item['NetworkSettings']['IPAddress'] }} >> hosts"
#   with_items: docker_containers

    # - name: Copy public SSH key
    #   include: ssh_key.yml ip_address={{ item['NetworkSettings']['IPAddress'] }}
    #   with_items: docker_containers

    # - name: Add the hosts
    #   add_host: name=new_host ansible_ssh_host={{ item['NetworkSettings']['IPAddress'] }} ansible_ssh_user=root ansible_ssh_pass={{ password }}
    #   with_items: docker_containers

# - name: Adding keys
#   hosts: new_host
#   tasks:
#     - name: Copy public SSH key
#       authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    # - name: Display IzP address and port mappings for containers
    #   # debug: msg={{inventory_hostname}}:{{item['HostConfig']['PortBindings']['8080/tcp'][0]['HostPort']}}
    #   # debug: msg={{inventory_hostname}}
    #   debug: msg={{item['NetworkSettings']['IPAddress']}}
    #   with_items: docker_containers

    # - name: Display IP address and port mappings for containers
    #   debug: msg={{inventory_hostname}}:{{item['HostConfig']['PortBindings']['8080/tcp'][0]['HostPort']}}
    #   with_items: docker_containers

